---
webservers:
  hosts:
    web1:
      ansible_host: 172.28.128.190

dbservers:
  hosts:
    db1:
      ansible_host: 172.28.128.247

all:
  vars:
    ansible_user: deploy
    ansible_ssh_private_key_file: ~/.ssh/deploy_id_rsa
    ansible_become: yes
    ansible_become_user: root
    ansible_become_method: sudo
