---
name: Destroy staging server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  tear_down_staging_srv:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
          
    - name: Authenticate with GCP
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Mask generated GCP values
      run: |
        echo "::add-mask::${{ env.CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE }}"
        echo "::add-mask::${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
        echo "::add-mask::${{ env.GOOGLE_GHA_CREDS_PATH }}"
        echo "::add-mask::${{ env.CLOUDSDK_CORE_PROJECT }}"
        echo "::add-mask::${{ env.CLOUDSDK_PROJECT }}"
        echo "::add-mask::${{ env.GCLOUD_PROJECT }}"
        echo "::add-mask::${{ env.GCP_PROJECT }}"
        echo "::add-mask::${{ env.GOOGLE_CLOUD_PROJECT }}" 
          
    - name: TEAR THIS BITCH DOWN
      working-directory: ./terraform
      run: |
        terraform init
        terraform destroy -auto-approve
