---
name: PHP CodeSniffer Auto Fix

on: [pull_request, workflow_dispatch]

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PHPLINT_TOKEN }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.10'
        extensions: mbstring, intl, gd, xml, ctype, zip
        tools: phpcs, phpcbf

    - name: Run PHP_CodeSniffer Fixer
      run: |
        phpcbf --standard=PSR2 . --ignore=vendor/* --error-severity=0 || echo "PHPCBF could not fix all violations"

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v5
      with:
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        delete-branch: true
        committer: GitHub <noreply@github.com>
        title: 'Automated PHPCBF Fixes'
        commit-message: 'Apply PHPCBF fixes'
        branch: 'phpcbf-fixes'
        token: ${{ secrets.PHPLINT_TOKEN }}
        base: ${{ github.head_ref }}
        labels: |
          phpcbf
          automated

    
    - name: Run PHP_CodeSniffer
      run: |
        if [[ "${{ steps.create-pr.outputs.pull-request-number }}" != "" ]]; then
          echo "A PR was created. Marking this step as failed."
          exit 1
        fi
        if phpcs --standard=PSR2 . --ignore=vendor/* --warning-severity=0 --error-severity=0; then
          echo "No coding standards errors found."
        else
          echo "Coding standards errors detected."
          exit 1
        fi



    
