- name: Install yum and cpan packages
  ansible.builtin.import_tasks: packages.yml
  tags: packages

- name: Import tasks from service.yml to start httpd
  ansible.builtin.import_tasks: service.yml
  tags: service

- name: Create folder for webapp
  ansible.builtin.file:
    path: /var/www/demo
    state: directory
    mode: "755"
  tags: create_webapp_folder
  notify: Clone git repo for webapp

- name: Flusing handlers to clone git repo if notified
  ansible.builtin.meta: flush_handlers

- name: Move webapp_vhost.conf to remote using template
  ansible.builtin.template:
    src: "webapp_vhost.conf.j2"
    dest: "/etc/httpd/conf.d/webapp_vhost.conf"
    owner: "apache"
    group: "apache"
    mode: "644"
  tags: move_files
  notify: Restart httpd


- name: Move production.yml to remote using template
  ansible.builtin.template:
    src: "production.yml.j2"
    dest: "/var/www/demo/environments/production.yml"
    owner: "apache"
    group: "apache"
    mode: "644"
  tags: move_files

- name: Move demod.service to remote using template
  ansible.builtin.template:
    src: "demod.service.j2"
    dest: "/etc/systemd/system/demod.service"
    owner: "root"
    group: "root"
    mode: "644"
  tags: move_files
  notify: Restart demod

- name: Install python packages needed for httpd_can_network_connect
  ansible.builtin.import_tasks: python_packages.yml
  tags: python_packages

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  tags: httpd_can_network_connect
