- name: Install yum and cpan packages
  ansible.builtin.import_tasks: packages.yml
  tags: yum_cpans

- name: Import tasks from service.yml to start httpd
  ansible.builtin.import_tasks: service.yml
  tags: service

- name: Create folder for webapp
  ansible.builtin.file:
    path: /var/www/demo
    state: directory
    mode: "755"
  tags: create_webapp_folder
  notify: Clone git repo for webapp

- name: Flusing handlers to clone git repo if notified
  ansible.builtin.meta: flush_handlers

- name: Move files to remote using template
  ansible.builtin.template:
    src: "{{ item.value.src }}"
    dest: "{{ item.value.dest }}"
    owner: "{{ item.value.owner | default(web_template.common.owner) }}"
    group: "{{ item.value.group | default(web_template.common.group) }}"
    mode: "{{ web_template.common.mode }}"
  loop: "{{ web_template.files | dict2items }}"
  loop_control:
    label: "{{ item.key }}: {{ item.value.src }} to {{ item.value.dest }}"
  tags: move_files

- name: Install python packages needed for httpd_can_network_connect
  ansible.builtin.import_tasks: python_packages.yml
  tags: python_packages

- name: Set httpd_can_network_connect flag on and keep it persistent across reboots
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true
  tags: httpd_can_network_connect
