apiVersion: v1
kind: Pod
metadata:
  name: my-image
  labels:
    app: my-image
spec:
  containers:
    - name: my-image
      image: ghcr.io/YOUR_USERNAME/my_container_registry/my_image
      imagePullPolicy: Always
  imagePullSecrets:
    - name: regcred
