---
- name: Playbook for installing and configuring a database server
  hosts: databas
  vars_files:
    - vault/passwords.yml
  tasks:
    - name: Make sure latest version of the MariaDB package is installed.
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - mariadb-server
        - MySQL-python

    - name: Start MariaDB on boot.
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started

    - name: Create db
      community.mysql.mysql_db:
        name: webappdb
        state: present

    - name: Create dbuser "webappuser"
      community.mysql.mysql_user:
        name: webappuser
        password: "{{ mysql_webappuser_password }}"
        state: present
        priv: '*.*:ALL,GRANT'
      become: true
      become_user: mysql

    - name: Copy over several files with loop
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"

      with_fileglob: "files/*.txt"
