- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start node_exporter
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
  - node_exporter.service
  - node_exporter.socket
  notify:
  - reload systemd
