---
- name: Create directory
  ansible.builtin.file:
    state: directory
    path: /home/{{ ansible_user }}/ansible-playground
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Copy file to uppercase destination
  ansible.builtin.copy:
    src: "files/index.html"
    dest: "/home/{{ ansible_user }}/ansible-playground/{{ 'index.html' | upper }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Get filename in return
  ansible.builtin.find:
    paths: /home/{{ ansible_user }}/ansible-playground/
    recurse: true
    patterns:
      - "INDEX.HTML"
  register: find_results

- name: Print directory path
  ansible.builtin.debug:
    msg: "{{ item.path }}"
  loop: "{{ find_results.files }}"
