name: Pytest

on:
  pull_request:
    branches:
        - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Build docker image
      run: |
        docker build -t pingurl_backend -f Docker/Dockerfile.backend .

    - name: Get host ip
      run: |
        echo "HOST_IP=$(ip addr show | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}' | cut -d/ -f1 | head -n 1)" >> $GITHUB_ENV

    - name: Run docker container
      run: |
        docker run -d -p 5000:5000 -e HOST_IP=$HOST_IP pingurl_backend

    - name: Analysing the code with pytest
      run: |
        pytest backend/
